description: Apache Cassandra is a free and open-source distributed database management
  system designed to handle large amounts of data across many commodity servers, providing
  high availability with no single point of failure.
engine: gotpl
home: http://cassandra.apache.org
icon: https://upload.wikimedia.org/wikipedia/commons/5/5e/Cassandra_logo.svg
keywords:
- cassandra
- database
- nosql
maintainers:
- email: goonohc@gmail.com
  name: Siri C
name: cassandra
version: 0.1.6
